---
- name: Start Jenkins
  service:
    name: jenkins
    state: started
- name: Add Jenkins to docker group
  command: usermod -aG docker jenkins
- name: Wait for port 8080 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 8080
    delay: 10
- name: Get Admin Password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  ignore_errors: True
