---
- name: Create a directory if it does not exist
  file:
    path: /opt/work
    state: directory
    mode: '0755'
- name: Create a directory for sonarqube-data mapping
  file:
    path: /etc/sonarqube-data
    state: directory
    mode: '0755'
- name: Make directory accessible by Docker
  command: chown -R 200 /etc/sonarqube-data
- name: Copy Docker Compose File to Work
  copy: 
    src: docker-compose.yml
    dest: /opt/work
    force: no
- name: Execute Docker Compose Command
  shell: docker-compose up -d
  args:
    chdir: /opt/work
- name: Wait for port 9000 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 9000
    delay: 10
